[versions]
ackpineCore = "0.7.1"
agp = "8.6.0"
androidx-activityCompose = "1.9.2"
androidx-appcompat = "1.7.0"
androidx-core-ktx = "1.13.1"
androidx-espresso-core = "3.6.1"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.1"
apksig = "8.5.2"
arsclib = "1.3.5"
bcpkixJdk15on = "1.70"
bom = "2024.09.01"
colorpickerCompose = "1.1.2"
datastorePreferences = "1.1.1"
junit = "4.13.2"
kotlin = "2.0.20"
ksp = "2.0.20-1.0.24"
material3Android = "1.3.0"
roomKtx = "2.6.1"
androidSvg = "1.4"

desugar-jdk-libs-nio = "2.1.2"

android-compileSdk = "34"
android-minSdk = "21"
android-targetSdk = "34"

[libraries]
ackpine-core = { module = "ru.solrudev.ackpine:ackpine-core", version.ref = "ackpineCore" }
ackpine-ktx = { module = "ru.solrudev.ackpine:ackpine-ktx", version.ref = "ackpineCore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "bom" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "material3Android" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
apksig = { module = "com.android.tools.build:apksig", version.ref = "apksig" }
arscLib = { module = "io.github.reandroid:ARSCLib", version.ref = "arsclib" }
bcpkix-jdk15on = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bcpkixJdk15on" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpickerCompose" }
android-svg = { module = "com.caverock:androidsvg", version.ref = "androidSvg" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }

android-tools-desugar-jdk-libs-nio = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugar-jdk-libs-nio" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }